local M = {}

M.translations = {
    en = {
        no_project = "[WYT] No project found in current directory. Please navigate to your project root.",
        config_updated = "[WYT] Configuration updated: ",
        provider_not_supported = "[WYT] Provider not supported.",
        result = "[WYT] Result:\n",
        set_provider = "Set LLM provider and API Key",
        generate_text = "Generate literary text using configured LLM",
        choose_lang = "Choose project language:",
        choose_type = "Choose literary text type:",
        choose_path = "Enter base path for the project:",
        choose_name = "Enter project name:",
        choose_content_type = "Choose main section content type:",
        content = "Content",
        definition = "Definition",
        has_sections = "Will the main section have sub-sections?",
        yes = "Yes",
        no = "No",
        open_where = "Open project in:",
        same_window = "Same window",
        new_window = "New window",
        plan_intro = "Project plan and guide.",
        text_intro = "Start writing your text here.",
        export_intro = "Final exported text.",
        project_created = "[WYT] Project created at: ",
        new_usage = "[WYT] Usage: :WYTNew p<tab>",
        new_desc = "Create new WYT entity ([p]roject, [i]dea, [g]roup, etc.)",
        idea_name = "Enter idea name:",
        use_llm = "Use LLM to improve/redact the idea?",
        add_to_group = "Add idea to an existing group?",
        idea_added = "[WYT] Idea added: ",
        no_ideas = "[WYT] No ideas found to group.",
        select_ideas = "Select ideas to group:",
        group_action = "Add to existing group or create new?",
        add_to_existing_group = "Add to existing group",
        create_new_group = "Create new group",
        select_group = "Select group:",
        edit_group_name = "Edit group name (leave blank to keep current)",
        new_group_name = "Enter new group name:",
        group_created = "[WYT] Group created: ",
        group_updated = "[WYT] Group updated: ",
        add_more_ideas = "Select more ideas to add to the group (optional):",
        ideas_synced = "[WYT] Ideas automatically synced from groups.",
        group_tags_updated = "[WYT] Group tags updated in existing ideas.",
        current_lang = "[WYT] Current language: ",
        sync_group_ideas_desc = "Automatically sync ideas from the group.",
        sync_complete = "[WYT] Sync complete.",
        move_idea_up = "Move idea up",
        move_idea_down = "Move idea down",
        goto_desc = "Navigate to a specific section in the project",
        goto_invalid_arg = "[WYT] Invalid argument. Use: plan, config, text, export, parent",
        goto_no_parent = "[WYT] No parent section.",
        goto_no_parent_plan = "[WYT] No plan.wyt.md found in parent section.",
        nav_desc = "Navigate through all files and sections of the WYT project",
        nav_select = "Select project file/section:",
        group_tag = "Group",
        groups_section = "Groups",
        ideas_section = "Ideas",
    },
    es = {
        no_project = "[WYT] No se encontró ningún proyecto en el directorio actual. Por favor, navega a la raíz de tu proyecto.",
        config_updated = "[WYT] Configuración actualizada: ",
        provider_not_supported = "[WYT] Proveedor no soportado.",
        result = "[WYT] Resultado:\n",
        set_provider = "Configura el proveedor LLM y la API Key",
        generate_text = "Genera texto literario usando el LLM configurado",
        choose_lang = "Elige el idioma del proyecto:",
        choose_type = "Elige el tipo de texto literario:",
        choose_path = "Ingresa la ruta base para el proyecto:",
        choose_name = "Ingresa el nombre del proyecto:",
        choose_content_type = "Elige el tipo de contenido de la sección principal:",
        content = "Contenido",
        definition = "Definición",
        has_sections = "¿La sección principal tendrá sub-secciones?",
        yes = "Sí",
        no = "No",
        open_where = "Abrir proyecto en:",
        same_window = "Misma ventana",
        new_window = "Nueva ventana",
        plan_intro = "Plan y guía del proyecto.",
        text_intro = "Comienza a escribir tu texto aquí.",
        export_intro = "Texto final exportado.",
        project_created = "[WYT] Proyecto creado en: ",
        new_usage = "[WYT] Uso: :WYTNew p<tab>",
        new_desc = "Crear nueva entidad WYT ([p]royecto, [i]dea, [g]rupo, etc.)",
        idea_name = "Ingresa el nombre de la idea:",
        use_llm = "¿Usar LLM para mejorar/redactar la idea?",
        add_to_group = "¿Agregar la idea a un grupo existente?",
        idea_added = "[WYT] Idea agregada: ",
        no_ideas = "[WYT] No se encontraron ideas para agrupar.",
        select_ideas = "Selecciona ideas para agrupar:",
        group_action = "¿Agregar a grupo existente o crear uno nuevo?",
        add_to_existing_group = "Agregar a grupo existente",
        create_new_group = "Crear nuevo grupo",
        select_group = "Selecciona el grupo:",
        edit_group_name = "Edita el nombre del grupo (deja vacío para mantenerlo)",
        new_group_name = "Ingresa el nombre del nuevo grupo:",
        group_created = "[WYT] Grupo creado: ",
        group_updated = "[WYT] Grupo actualizado: ",
        add_more_ideas = "Selecciona más ideas para agregar al grupo (opcional):",
        ideas_synced = "[WYT] Ideas sincronizadas automáticamente desde grupos.",
        group_tags_updated = "[WYT] Marcas de grupo actualizadas en ideas existentes.",
        current_lang = "[WYT] Idioma actual: ",
        sync_group_ideas_desc = "Sincronizar automáticamente ideas del grupo.",
        sync_complete = "[WYT] Sincronización completa.",
        move_idea_down = "Mover idea abajo",
        move_idea_up = "Mover idea arriba",
        goto_desc = "Navegar a una sección específica del proyecto",
        goto_invalid_arg = "[WYT] Argumento inválido. Usa: plan, config, text, export, parent",
        goto_no_parent = "[WYT] No hay sección padre.",
        goto_no_parent_plan = "[WYT] No se encontró plan.wyt.md en la sección padre.",
        nav_desc = "Navega entre todos los archivos y secciones del proyecto WYT",
        nav_select = "Selecciona archivo/sección del proyecto:",
        group_tag = "Grupo",
        groups_section = "Grupos",
        ideas_section = "Ideas",
    }
}

M.lang = "en"

function M.set_lang(lang)
    if M.translations[lang] then
        M.lang = lang
    end
end

function M.t(key, lang)
    lang = lang or M.lang
    return M.translations[lang][key] or key
end


function M.get_lang()
    return M.lang
end

return M
